CHICAGO_COMMUNITY_AREA_CODE_TO_NAME = {
    9: "Edison Park",
    2: "West Ridge",
    1: "Rogers Park",
    12: "Forest Glen",
    13: "North Park",
    4: "Lincoln Square",
    77: "Edgewater",
    76: "O'Hare",
    10: "Norwood Park",
    11: "Jefferson Park",
    14: "Albany Park",
    3: "Uptown",
    17: "Dunning",
    15: "Portage Park",
    16: "Irving Park",
    21: "Avondale",
    5: "North Center",
    6: "Lake View",
    18: "Montclar",
    19: "Belmont Cragin",
    20: "Hermosa",
    22: "Logan Square",
    7: "Lincoln Park",
    25: "Austin",
    23: "Humboldt Park",
    24: "West Town",
    8: "Near North Side",
    26: "West Garfield Park",
    27: "East Garfield Park",
    28: "Near West Side",
    32: "Loop",
    30: "South Lawndale",
    29: "North Lawndale",
    31: "Lower West Side",
    33: "Near South Side",
    57: "Archer Heights",
    58: "Brighton Park",
    59: "McKinley Park",
    60: "Bridgeport",
    34: "Armour Square",
    35: "Douglas",
    56: "Garfield Ridge",
    63: "Gage Park",
    62: "West Edison",
    61: "New City",
    37: "Fuller Park",
    38: "Grand Boulevard",
    36: "Oakland",
    64: "Clearing",
    65: "West Lawn",
    66: "Chicago Lawn",
    67: "West Englewood",
    40: "Washington Park",
    39: "Kenwood",
    41: "Hyde Park", 
    68: "Englewood",
    69: "Greater Grand Crossing",
    45: "Avalon Park",
    42: "Woodlawn",
    43: "South Shore",
    70: "Ashburn",
    71: "Auburn Gresham",
    44: "Chatham",
    47: "Burnside",
    48: "Calumet Heights",
    46: "South Chicago",
    72: "Beverly",
    73: "Washington Heights",
    49: "Roseland",
    50: "Pullman",
    51: "South Deering",
    52: "East Side",
    74: "Mount Greenwood",
    75: "Morgan Park",
    53: "West Pullman",
    54: "Riverdale",
    55: "Hegewisch"
}